from django.db import models

class Trip(models.Model):
    startdatedate = models.CharField(max_length =28,default='', null=True)
    startpickup_address = models.CharField(max_length=111,default='', null=True)
    startpickup_locationtype = models.CharField(max_length=5,default='', null=True)
    startpickup_locationcoordinates0=models.DecimalField(max_digits=18, decimal_places=14, null=True)
    startpickup_locationcoordinates1=models.DecimalField(max_digits=18, decimal_places=16, null=True)
    enddate=models.CharField(max_length=30,default='', null=True)
    endpickup_address=models.CharField(max_length=131,default='', null=True)
    endpickup_locationtype=models.CharField(max_length=5,default='', null=True)
    endpickup_locationcoordinates0=models.DecimalField(max_digits=18, decimal_places=14, null=True)
    endpickup_locationcoordinates1=models.DecimalField(max_digits=18, decimal_places=16, null=True)
    countryname=models.CharField(max_length=8,default='', null=True)
    cityname=models.CharField(max_length=12,default='', null=True)
    passengerfirst_name=models.CharField(max_length=19,default='', null=True)
    passengerlast_name=models.CharField(max_length=20,default='', null=True)
    driverfirst_name=models.CharField(max_length=19,default='', null=True)
    driverlast_name=models.CharField(max_length=23,default='', null=True)
    carplate=models.CharField(max_length=7,default='', null=True)
    status=models.CharField(max_length=7,default='', null=True)
    check_code=models.IntegerField()
    createdAtdate=models.CharField(max_length=28,default='', null=True)
    updatedAtdate=models.CharField(max_length=28,default='', null=True)
    price=models.IntegerField()
    driver_locationtype=models.CharField(max_length=5,default='', null=True)
    driver_locationcoordinates0=models.DecimalField(max_digits=18, decimal_places=14, null=True)
    driver_locationcoordinates1=models.DecimalField(max_digits=18, decimal_places=16, null=True)
    driver_location=models.CharField(max_length=30,default='', null=True)
    