# Generated by Django 3.1 on 2020-08-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=100)),
                ('end', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('passenger', models.CharField(default='', max_length=100)),
                ('driver', models.CharField(default='', max_length=100)),
                ('car', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=10)),
                ('check_code', models.CharField(default='', max_length=3)),
                ('createdAt', models.CharField(default='', max_length=3)),
                ('updatedAt', models.CharField(default='', max_length=3)),
                ('price', models.IntegerField()),
                ('driver_location', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
