# Generated by Django 3.1 on 2020-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='car',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='trip',
            name='car_plate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='city_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='trip',
            name='country_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='trip',
            name='createdAt_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_location_coordinates',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_location_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_pickup_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_pickup_location_coordinates',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_pickup_location_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger_last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_pickup_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_pickup_location_coordinates',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_pickup_location_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='updatedAt_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
