# Generated by Django 3.1 on 2020-08-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200824_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='driver_first_name',
            new_name='driver_location',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='driver_last_name',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='createdAt_date',
            new_name='passengerlast_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='car_plate',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_location_coordinates',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_location_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_pickup_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_pickup_location_coordinates',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_pickup_location_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passenger_first_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passenger_last_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_pickup_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_pickup_location_coordinates',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_pickup_location_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updatedAt_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='carplate',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='trip',
            name='cityname',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='countryname',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='createdAtdate',
            field=models.CharField(default='', max_length=28),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_locationcoordinates0',
            field=models.DecimalField(decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_locationcoordinates1',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_locationtype',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='driverfirst_name',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='trip',
            name='driverlast_name',
            field=models.CharField(default='', max_length=23),
        ),
        migrations.AddField(
            model_name='trip',
            name='endpickup_address',
            field=models.CharField(default='', max_length=131),
        ),
        migrations.AddField(
            model_name='trip',
            name='endpickup_locationcoordinates0',
            field=models.DecimalField(decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='endpickup_locationcoordinates1',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='endpickup_locationtype',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='passengerfirst_name',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='trip',
            name='startdatedate',
            field=models.CharField(default='', max_length=28),
        ),
        migrations.AddField(
            model_name='trip',
            name='startpickup_address',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='trip',
            name='startpickup_locationcoordinates0',
            field=models.DecimalField(decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='startpickup_locationcoordinates1',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='startpickup_locationtype',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='updatedAtdate',
            field=models.CharField(default='', max_length=28),
        ),
        migrations.AlterField(
            model_name='trip',
            name='check_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='', max_length=7),
        ),
    ]
