# Generated by Django 3.1 on 2020-08-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200824_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver_location',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdatedate',
            field=models.CharField(default='', max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startpickup_address',
            field=models.CharField(default='', max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startpickup_locationtype',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
