# Generated by Django 3.1 on 2020-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20200824_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='carplate',
            field=models.CharField(default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cityname',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='countryname',
            field=models.CharField(default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='createdAtdate',
            field=models.CharField(default='', max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver_locationtype',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driverfirst_name',
            field=models.CharField(default='', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driverlast_name',
            field=models.CharField(default='', max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='endpickup_address',
            field=models.CharField(default='', max_length=131, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='endpickup_locationtype',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passengerfirst_name',
            field=models.CharField(default='', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passengerlast_name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updatedAtdate',
            field=models.CharField(default='', max_length=28, null=True),
        ),
    ]
